project:
  type: website

website:
  title: "Outsider Data Science"
  navbar:
    left:
      - text: Blog
        file: index.qmd
      - text: About
        file: about.qmd

format:
  html:
    theme:
      light: spacelab
      dark: darkly
    css: styles.css
    toc: true
    code-block-bg: true
    code-block-border-left: "#31BAE9"

editor: source
freeze: auto

