project:
  type: website

website:
  title: "Outsider Data Science"
  navbar:
    left:
      - text: Blog
        file: index.qmd
      - text: About
        file: about.qmd
      - icon: linkedin
        href: "https://www.linkedin.com/in/asteinmetz/"
      - icon: twitter
        href: "https://twitter.com/adababbage"
      - icon: mastodon
        href: "https://fosstodon.org/@adababbage"
      - icon: github
        href: "https://github.com/apsteinmetz"


format:
  html:
    theme:
      dark: darkly
      light: cerulean
    css: styles.css
    toc: true
    code-block-bg: true
    code-block-border-left: "#31BAE9"

editor: source
freeze: auto

