project:
  type: website

website:
  title: "Outsider Data Science"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: spacelab
    css: styles.css
    toc: true
    code-block-bg: true
    code-block-border-left: "#31BAE9"

editor: source
freeze: true

